name: Ingest Reports

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch: {}       # allow manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install feedparser requests beautifulsoup4 psycopg2-binary python-dateutil
      - name: Run ingest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKFILL_DAYS: "30"
        run: python scripts/ingest.py
